### ISSUE TITLE
🗓🖍Style the datepicker UI component - Day and Month select fields (2/3)

### ISSUE THREAD

**Issue by hemchander23** [freshhuddle/fw-ui#10]
## How it looks now
Currently, the Datepicker UI component looks like this : 
Although functional, it lacks the styling for the **month & year select tag** and its options. 

![image](https://user-images.githubusercontent.com/19341550/66234063-5e579c80-e70a-11e9-9d41-908ca3616f15.png)

## What we want it to be (Styling - Refer _end state_ image at the bottom for TL:DR;)
1. The Year and Month dropdown has to have a white background with some shadow and nice highlight for its options (green arrow - hover state, cyan arrow - selected state)

<img width="438" alt="Screenshot 2019-10-05 at 12 49 44 AM" src="https://user-images.githubusercontent.com/19341550/66234168-98c13980-e70a-11e9-9487-f0b17ee6a2d3.png">

2. The select options have to be scrollable. Example year select tag where we need to show past 100 years without having all the options listed like a tower

## End State

<img width="330" alt="Screenshot 2019-10-05 at 12 49 28 AM" src="https://user-images.githubusercontent.com/19341550/66234115-74fdf380-e70a-11e9-9a19-078f07e6da1e.png">

We are using this datepicker -> http://www.daterangepicker.com/
You can inspect the DOM and add custom styles

You can also solve #9 if you are curious !!

**Comment by hemchander23** [comment]
Follow the contribution guidelines [mentioned here](https://github.com/freshhuddle/fw-input#to-contribute) before you start hacking ♥

**Comment by viettrung9012** [comment]
I can work on this issue if no one claimed it yet

**Comment by hemchander23** [comment]
Hi @viettrung9012 

Forgot to update the message here. I am currently replacing the datepicker with a new one that supports styling. Will update once it is done :) ! Closing this issue temporarily

**Comment by hemchander23** [comment]
Hi @viettrung9012

Thanks for showing interest !! Forgot to update the message here. I am currently replacing the datepicker with a new one that supports styling. Will update once it is done :) ! Closing this issue temporarily
