### ISSUE TITLE
[New UI Component] Let's create a Tag

### ISSUE THREAD

**Issue by hemchander23** [freshhuddle/fw-ui#12]
Let's build an **fw-tag** component using StencilJS that looks like this

![image](https://user-images.githubusercontent.com/19341550/66296701-c5906f00-e90b-11e9-9299-3202f529aa09.png)

Attributes for fw-tag are 

_text_ - The text that is shown in the tag
_state_ - Represents the color of the tag. Starting from left ->`information`, `success`, `error`, `warning`, `neutral`,`default`
_tooltip_ - The tooltip for the tag (optional)

Refer the documentation which explains how easy it is to create a component -> https://stenciljs.com/docs/my-first-component

You can create a component directory and add it here -> https://github.com/freshhuddle/fw-ui/tree/dev/src/components

Note: Make sure you follow the guidelines [mentioned here](https://github.com/freshhuddle/fw-ui#to-contribute) before submitting PR. You'll also find the samples for input (fw-input) and datepicker (fw-datepicker) already!

**Comment by GabriFedi** [comment]
which is the font of the text?

**Comment by hemchander23** [comment]
Hi @GabriFedi,

Thanks for showing interest! Let's stick to system fonts. 
`-apple-system,BlinkMacSystemFont,"Segoe UI", Roboto,"Helvetica Neue",Arial,sans-serif`

**Comment by GabriFedi** [comment]
here you go https://github.com/GabriFedi/fw-ui

**Comment by hemchander23** [comment]
Amazing @GabriFedi ! Merged
