### ISSUE TITLE
[Enhancement] Adding error and warning state to the input UI component 

### ISSUE THREAD

**Issue by hemchander23** [freshhuddle/fw-ui#4]
We need to add `state` to the input UI component. 

**How to achieve that**
1. Follow the contribution guidelines [mentioned here](https://github.com/freshhuddle/fw-input#to-contribute)
2. We need to add a new property `state` to the TSX file (see the cyan arrow). This will take the following values - normal (default), warning and error. 
3. Similar to what we did for `required` property, we can use a ternary operator to add classes to input tag and .stateText div tag. These classes can be defined in the fw-input.css file with the approporiate style (for ex: .warning-input , .error-input)
4. For error, use the color _persimmon_ in variables.css file. For warning use, _sunrise_. As you might have already figured out, they are CSS variables. The background color can be the same with low alpha. 

![image](https://user-images.githubusercontent.com/19341550/66154802-e9b62c80-e63b-11e9-84b9-74ec08505593.png)
 
**How it should look like**
Ideally, if I add a state attribute to the tag, it should look like this
![image](https://user-images.githubusercontent.com/19341550/66155880-34d13f00-e63e-11e9-9636-7f6c49039311.png)

![image](https://user-images.githubusercontent.com/19341550/66154134-76f88180-e63a-11e9-82fa-32e96e5daa9f.png)

You can read more about Stencil properties [here](https://stenciljs.com/docs/properties). Thanks for contributing!

**Comment by atrievel** [comment]
@hemchander23 I can tackle this if no one else has yet. Thanks!

**Comment by hemchander23** [comment]
@atrievel Thanks! You can take this one up 😃
